config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :projects
  resources :employees

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'employees#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    added_attrs = [:name, :job_description, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def index
    @users = User.all
  end

  def show
    set_user
    @projects = Project.all
  end

  def new
    @user = User.new
  end

#   # GET /employees/1/edit
#   def edit
#   end

#   # POST /employees
#   # POST /employees.json
#   def create
#     @employee = Employee.new(employee_params)

#     respond_to do |format|
#       if @employee.save
#         format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
#         format.json { render :show, status: :created, location: @employee }
#       else
#         format.html { render :new }
#         format.json { render json: @employee.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PATCH/PUT /employees/1
#   # PATCH/PUT /employees/1.json
#   def update
#     respond_to do |format|
#       if @employee.update(employee_params)
#         format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
#         format.json { render :show, status: :ok, location: @employee }
#       else
#         format.html { render :edit }
#         format.json { render json: @employee.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /employees/1
#   # DELETE /employees/1.json
#   def destroy
#     @employee.destroy
#     respond_to do |format|
#       format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.fetch(:employee, {})
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end
  def new
    @project = Project.new
  end

  def create
    user = current_user
    @project = user.projects.create(project_params)
    redirect_to projects_path
  end

  def edit
    @project = Project.find(params[:id])
    count = @project.endorsement + 1
    @project.update(endorsement: count)
    redirect_to projects_path
  end

  def update
    @project = Project.find(params[:id])
    count = @project.update
    @project.update(endorsement: count)
  end

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/employees/_form.html.erb
<%= form_for(employee) do |f| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
    <p id="notice"><%= notice %></p>

<h1 class="text-center">Employees</h1>
    <% @users.each do |employee| %>
    <div class="text-center">
      <hr>
      <h3><%= link_to employee.name, employee_path(employee) %><h3>
      <h5><%= employee.job_description  %><h5>
    </div>
    <% end %>

app/views/employees/new.html.erb
<div class="text-center">
  <%= form_for Project.new do |form| %>
    <%= form.text_field :title, :required => true, placeholder: "title" %><br><br>
    <%= form.text_area :description,  :required => true, placeholder: "description" %><br><br>
    <%= form.submit %>
  <% end %>
</div>
<br>
<button type="button" class="btn btn-default center-block">
    <%= link_to 'Back', employees_path%>
</button>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<div class="employee-info text-center">
  <%= @user.name %><br>
  <%= @user.job_description %><br>
  <%= @user.email %>
</div>

<div class="projects text-center">
  <% @projects.each do |project| %>
    <div class='project-detail'>
      <hr>
      <h3><%= @project.title %></h3><br>
      <p><%= @project.description %></p>
    </div>
  <% end %>
</div>

<br>

<!-- <%= link_to 'Edit', edit_employee_path(@user) %> -->
<button type="button" class="btn btn-default center-block">
    <%= link_to 'Back', employees_path%>
</button>
<br>

<button type="button" class="btn btn-default center-block">
  <%= link_to 'Add project', new_employee_path %>
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PerformanceManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<div class="text-center">
<h1>Projects</h1>

    <% @projects.each do |project| %>
      <hr>
      <h3><%= project.title %></h3>
      <%= project.description  %>
      <%= project.endorsement %>
      <%= link_to "Endorse", edit_project_path(project) %><br/>

    <% end %>
  </div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">

   <div class="navbar-header">
      <div class="navbar-brand"><%= link_to 'Employee page', employees_path %></div>
    </div>



   <div class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to 'sign out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'sign in', new_user_session_path %></li>
        <li><%= link_to 'sign up', new_user_registration_path %></li>
      <% end %>
    </div>

 </div><!-- /.container-fluid -->
</nav>